# Generated by Django 4.2.6 on 2023-11-14 21:56

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_alter_customer_birthday'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='customer',
            index=django.contrib.postgres.indexes.HashIndex(fields=['birthday'], name='customers_c_birthda_eaf0c8_hash'),
        ),
    ]
