# Generated by Django 4.2.6 on 2023-11-14 22:34

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_remove_customer_customers_c_birthda_eaf0c8_hash_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='birthday',
            field=models.DateField(),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=django.contrib.postgres.indexes.HashIndex(fields=['birthday'], name='customers_c_birthda_eaf0c8_hash'),
        ),
    ]
