# Generated by Django 4.2.6 on 2023-11-14 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_alter_customer_birthday_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='customer',
            name='customers_c_birthda_eaf0c8_hash',
        ),
    ]
